name: Staging Deploy

on:
  push:
    branches:
      - main

jobs:
  preview-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          yarn install --immutable
          VITE_MODE=staging yarn build
      - name: Deploy to staging
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: idp-fe-stg
          directory: build
          gitHubToken: ${{ github.token }}
